/*
 * Spotify Web API
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AudioAnalysisObjectMeta;
import com.konfigthis.client.model.AudioAnalysisObjectTrack;
import com.konfigthis.client.model.SectionObject;
import com.konfigthis.client.model.SegmentObject;
import com.konfigthis.client.model.TimeIntervalObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AudioAnalysisObject
 */
public class AudioAnalysisObjectTest {
    private final AudioAnalysisObject model = new AudioAnalysisObject();

    /**
     * Model tests for AudioAnalysisObject
     */
    @Test
    public void testAudioAnalysisObject() {
        // TODO: test AudioAnalysisObject
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'track'
     */
    @Test
    public void trackTest() {
        // TODO: test track
    }

    /**
     * Test the property 'bars'
     */
    @Test
    public void barsTest() {
        // TODO: test bars
    }

    /**
     * Test the property 'beats'
     */
    @Test
    public void beatsTest() {
        // TODO: test beats
    }

    /**
     * Test the property 'sections'
     */
    @Test
    public void sectionsTest() {
        // TODO: test sections
    }

    /**
     * Test the property 'segments'
     */
    @Test
    public void segmentsTest() {
        // TODO: test segments
    }

    /**
     * Test the property 'tatums'
     */
    @Test
    public void tatumsTest() {
        // TODO: test tatums
    }

}
