openapi: 3.0.3
info:
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
  description: |
    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

    The base URI for all Web API requests is `https://api.spotify.com/v1`.

    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.
  termsOfService: https://developer.spotify.com/terms/
  title: Spotify Web API
  version: 1.0.0
  x-konfig-ignore:
    object-with-no-properties: true
  x-konfig-has-globally-required-security: true
servers:
- url: https://api.spotify.com/v1
tags:
- name: Library
- name: Tracks
- name: Playlists
- name: Player
- name: Users
- name: Albums
- name: Artists
- name: Audiobooks
- name: Episodes
- name: Shows
- name: Categories
- name: Chapters
- name: Genres
- name: Markets
- name: Search
paths:
  /albums/{id}:
    get:
      description: |
        Get Spotify catalog information for a single album.
      operationId: Albums_getInformation
      security:
      - oauth_2_0: []
      summary: |
        Get Album
      tags:
      - Albums
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--albums-id
      x-accepts: application/json
  /albums:
    get:
      description: |
        Get Spotify catalog information for multiple albums identified by their Spotify IDs.
      operationId: Albums_listSeveral
      security:
      - oauth_2_0: []
      summary: |
        Get Several Albums
      tags:
      - Albums
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--albums
      x-accepts: application/json
  /albums/{id}/tracks:
    get:
      description: |
        Get Spotify catalog information about an album’s tracks.
        Optional parameters can be used to limit the number of tracks returned.
      operationId: Albums_getTracksById
      security:
      - oauth_2_0: []
      summary: |
        Get Album Tracks
      tags:
      - Albums
      - Tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--albums-id-tracks
      x-accepts: application/json
  /artists/{id}:
    get:
      description: |
        Get Spotify catalog information for a single artist identified by their unique Spotify ID.
      operationId: Artists_getCatalogInfo
      security:
      - oauth_2_0: []
      summary: |
        Get Artist
      tags:
      - Artists
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--artists-id
      x-accepts: application/json
  /artists:
    get:
      description: |
        Get Spotify catalog information for several artists based on their Spotify IDs.
      operationId: Artists_getCatalogInfo
      security:
      - oauth_2_0: []
      summary: |
        Get Several Artists
      tags:
      - Artists
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--artists
      x-accepts: application/json
  /artists/{id}/albums:
    get:
      description: |
        Get Spotify catalog information about an artist's albums.
      operationId: Artists_getAlbumsById
      security:
      - oauth_2_0: []
      summary: |
        Get Artist's Albums
      tags:
      - Artists
      - Albums
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--artists-id-albums
      x-accepts: application/json
  /artists/{id}/top-tracks:
    get:
      description: |
        Get Spotify catalog information about an artist's top tracks by country.
      operationId: Artists_getTopTracks
      security:
      - oauth_2_0: []
      summary: |
        Get Artist's Top Tracks
      tags:
      - Artists
      - Tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--artists-id-top-tracks
      x-accepts: application/json
  /artists/{id}/related-artists:
    get:
      description: |
        Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community's listening history.
      operationId: Artists_getRelatedArtists
      security:
      - oauth_2_0: []
      summary: |
        Get Artist's Related Artists
      tags:
      - Artists
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--artists-id-related-artists
      x-accepts: application/json
  /shows/{id}:
    get:
      description: |
        Get Spotify catalog information for a single show identified by its
        unique Spotify ID.
      operationId: Shows_getInformation
      security:
      - oauth_2_0:
        - user-read-playback-position
      summary: |
        Get Show
      tags:
      - Shows
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--shows-id
      x-accepts: application/json
  /shows:
    get:
      description: |
        Get Spotify catalog information for several shows based on their Spotify IDs.
      operationId: Shows_getMultipleShowsInfo
      security:
      - oauth_2_0: []
      summary: |
        Get Several Shows
      tags:
      - Shows
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--shows
      x-accepts: application/json
  /shows/{id}/episodes:
    get:
      description: |
        Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
      operationId: Shows_getEpisodesById
      security:
      - oauth_2_0:
        - user-read-playback-position
      summary: |
        Get Show Episodes
      tags:
      - Shows
      - Episodes
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--shows-id-episodes
      x-accepts: application/json
  /episodes/{id}:
    get:
      description: |
        Get Spotify catalog information for a single episode identified by its
        unique Spotify ID.
      operationId: Episodes_getSingleById
      security:
      - oauth_2_0:
        - user-read-playback-position
      summary: |
        Get Episode
      tags:
      - Episodes
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--episodes-id
      x-accepts: application/json
  /episodes:
    get:
      description: |
        Get Spotify catalog information for several episodes based on their Spotify IDs.
      operationId: Episodes_getSeveral
      security:
      - oauth_2_0:
        - user-read-playback-position
      summary: |
        Get Several Episodes
      tags:
      - Episodes
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--episodes
      x-accepts: application/json
  /audiobooks/{id}:
    get:
      description: |
        Get Spotify catalog information for a single audiobook. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
      operationId: Audiobooks_getCatalogInfo
      security:
      - oauth_2_0: []
      summary: |
        Get an Audiobook
      tags:
      - Audiobooks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--audiobooks-id
      x-accepts: application/json
  /audiobooks:
    get:
      description: |
        Get Spotify catalog information for several audiobooks identified by their Spotify IDs. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
      operationId: Audiobooks_getSeveral
      security:
      - oauth_2_0: []
      summary: |
        Get Several Audiobooks
      tags:
      - Audiobooks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--audiobooks
      x-accepts: application/json
  /audiobooks/{id}/chapters:
    get:
      description: |
        Get Spotify catalog information about an audiobook's chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
      operationId: Audiobooks_getChaptersById
      security:
      - oauth_2_0: []
      summary: |
        Get Audiobook Chapters
      tags:
      - Audiobooks
      - Chapters
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--audiobooks-id-chapters
      x-accepts: application/json
  /me/audiobooks:
    delete:
      description: |
        Remove one or more audiobooks from the Spotify user's library.
      operationId: Audiobooks_removeFromLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Remove User's Saved Audiobooks
      tags:
      - Audiobooks
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--me-audiobooks
      x-accepts: application/json
    get:
      description: |
        Get a list of the audiobooks saved in the current Spotify user's 'Your Music' library.
      operationId: Audiobooks_listSaved
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Get User's Saved Audiobooks
      tags:
      - Audiobooks
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-audiobooks
      x-accepts: application/json
    put:
      description: |
        Save one or more audiobooks to the current Spotify user's library.
      operationId: Audiobooks_saveCurrentUserLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Save Audiobooks for Current User
      tags:
      - Audiobooks
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-audiobooks
      x-accepts: application/json
  /me/audiobooks/contains:
    get:
      description: |
        Check if one or more audiobooks are already saved in the current Spotify user's library.
      operationId: Audiobooks_checkUserSaved
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Check User's Saved Audiobooks
      tags:
      - Audiobooks
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-audiobooks-contains
      x-accepts: application/json
  /chapters/{id}:
    get:
      description: |
        Get Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
      operationId: Chapters_getChapterInfo
      security:
      - oauth_2_0: []
      summary: |
        Get a Chapter
      tags:
      - Chapters
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--chapters-id
      x-accepts: application/json
  /chapters:
    get:
      description: |
        Get Spotify catalog information for several audiobook chapters identified by their Spotify IDs. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
      operationId: Chapters_getMultipleByIds
      security:
      - oauth_2_0: []
      summary: |
        Get Several Chapters
      tags:
      - Chapters
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--chapters
      x-accepts: application/json
  /tracks/{id}:
    get:
      description: |
        Get Spotify catalog information for a single track identified by its
        unique Spotify ID.
      operationId: Tracks_getBySpotifyId
      security:
      - oauth_2_0: []
      summary: |
        Get Track
      tags:
      - Tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--tracks-id
      x-accepts: application/json
  /tracks:
    get:
      description: |
        Get Spotify catalog information for multiple tracks based on their Spotify IDs.
      operationId: Tracks_getMultipleByIds
      security:
      - oauth_2_0: []
      summary: |
        Get Several Tracks
      tags:
      - Tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--tracks
      x-accepts: application/json
  /search:
    get:
      description: |
        Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks
        that match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
      operationId: Search_spotifyCatalogInfo
      security:
      - oauth_2_0: []
      summary: |
        Search for Item
      tags:
      - Search
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--search
      x-accepts: application/json
  /me:
    get:
      description: |
        Get detailed profile information about the current user (including the
        current user's username).
      operationId: Users_getCurrentUserProfile
      security:
      - oauth_2_0:
        - user-read-private
        - user-read-email
      summary: |
        Get Current User's Profile
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me
      x-accepts: application/json
  /playlists/{playlist_id}:
    get:
      description: |
        Get a playlist owned by a Spotify user.
      operationId: Playlists_getPlaylistById
      security:
      - oauth_2_0: []
      summary: |
        Get Playlist
      tags:
      - Playlists
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--playlists-playlist_id
      x-accepts: application/json
    put:
      description: |
        Change a playlist's name and public/private state. (The user must, of
        course, own the playlist.)
      operationId: Playlists_updateDetails
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Change Playlist Details
      tags:
      - Playlists
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--playlists-playlist_id
      x-content-type: application/json
      x-accepts: application/json
  /playlists/{playlist_id}/tracks:
    delete:
      description: |
        Remove one or more items from a user's playlist.
      operationId: Playlists_removeItems
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Remove Playlist Items
      tags:
      - Playlists
      - Tracks
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--playlists-playlist_id-tracks
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: |
        Get full details of the items of a playlist owned by a Spotify user.
      operationId: Playlists_getPlaylistItems
      security:
      - oauth_2_0:
        - playlist-read-private
      summary: |
        Get Playlist Items
      tags:
      - Playlists
      - Tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--playlists-playlist_id-tracks
      x-accepts: application/json
    post:
      description: |
        Add one or more items to a user's playlist.
      operationId: Playlists_addItems
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Add Items to Playlist
      tags:
      - Playlists
      - Tracks
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
    put:
      description: |
        Either reorder or replace items in a playlist depending on the request's parameters.
        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.
        To replace items, include `uris` as either a query parameter or in the request's body.
        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.
        <br/>
        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.
        These operations can't be applied together in a single request.
      operationId: Playlists_updatePlaylistItems
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Update Playlist Items
      tags:
      - Playlists
      - Tracks
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
  /me/playlists:
    get:
      description: |
        Get a list of the playlists owned or followed by the current Spotify
        user.
      operationId: Playlists_getUserPlaylists
      security:
      - oauth_2_0:
        - playlist-read-private
      summary: |
        Get Current User's Playlists
      tags:
      - Playlists
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-playlists
      x-accepts: application/json
  /me/albums:
    delete:
      description: |
        Remove one or more albums from the current user's 'Your Music' library.
      operationId: Albums_removeSaved
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Remove Users' Saved Albums
      tags:
      - Albums
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: |
        Get a list of the albums saved in the current Spotify user's 'Your Music' library.
      operationId: Albums_getSaved
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Get User's Saved Albums
      tags:
      - Albums
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-albums
      x-accepts: application/json
    put:
      description: |
        Save one or more albums to the current user's 'Your Music' library.
      operationId: Albums_saveCurrentUserLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Save Albums for Current User
      tags:
      - Albums
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
  /me/albums/contains:
    get:
      description: |
        Check if one or more albums is already saved in the current Spotify user's 'Your Music' library.
      operationId: Albums_checkSaved
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Check User's Saved Albums
      tags:
      - Albums
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-albums-contains
      x-accepts: application/json
  /me/tracks:
    delete:
      description: |
        Remove one or more tracks from the current user's 'Your Music' library.
      operationId: Tracks_removeFromLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Remove User's Saved Tracks
      tags:
      - Tracks
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: |
        Get a list of the songs saved in the current Spotify user's 'Your Music' library.
      operationId: Tracks_getUserSaved
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Get User's Saved Tracks
      tags:
      - Tracks
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-tracks
      x-accepts: application/json
    put:
      description: |
        Save one or more tracks to the current user's 'Your Music' library.
      operationId: Tracks_saveForCurrentUser
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Save Tracks for Current User
      tags:
      - Tracks
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
  /me/tracks/contains:
    get:
      description: |
        Check if one or more tracks is already saved in the current Spotify user's 'Your Music' library.
      operationId: Tracks_checkSaved
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Check User's Saved Tracks
      tags:
      - Tracks
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-tracks-contains
      x-accepts: application/json
  /me/episodes:
    delete:
      description: |
        Remove one or more episodes from the current user's library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: Episodes_removeFromLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Remove User's Saved Episodes
      tags:
      - Episodes
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: |
        Get a list of the episodes saved in the current Spotify user's library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: Episodes_getUserSavedEpisodes
      security:
      - oauth_2_0:
        - user-library-read
        - user-read-playback-position
      summary: |
        Get User's Saved Episodes
      tags:
      - Episodes
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-episodes
      x-accepts: application/json
    put:
      description: |
        Save one or more episodes to the current user's library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: Episodes_saveCurrentUserLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Save Episodes for Current User
      tags:
      - Episodes
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
  /me/episodes/contains:
    get:
      description: |
        Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.<br/>
        This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
      operationId: Episodes_checkSavedEpisodes
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Check User's Saved Episodes
      tags:
      - Episodes
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-episodes-contains
      x-accepts: application/json
  /me/shows:
    delete:
      description: |
        Delete one or more shows from current Spotify user's library.
      operationId: Shows_removeUserLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Remove User's Saved Shows
      tags:
      - Shows
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--me-shows
      x-accepts: application/json
    get:
      description: |
        Get a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.
      operationId: Shows_getUserSavedShows
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Get User's Saved Shows
      tags:
      - Shows
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-shows
      x-accepts: application/json
    put:
      description: |
        Save one or more shows to current Spotify user's library.
      operationId: Shows_saveCurrentUserLibrary
      security:
      - oauth_2_0:
        - user-library-modify
      summary: |
        Save Shows for Current User
      tags:
      - Shows
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-shows
      x-accepts: application/json
  /me/shows/contains:
    get:
      description: |
        Check if one or more shows is already saved in the current Spotify user's library.
      operationId: Shows_checkSavedShows
      security:
      - oauth_2_0:
        - user-library-read
      summary: |
        Check User's Saved Shows
      tags:
      - Shows
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-shows-contains
      x-accepts: application/json
  /me/top/{type}:
    get:
      description: |
        Get the current user's top artists or tracks based on calculated affinity.
      operationId: Users_getTopItems
      security:
      - oauth_2_0:
        - user-top-read
      summary: |
        Get User's Top Items
      tags:
      - Users
      - Tracks
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-top-type
      x-accepts: application/json
  /users/{user_id}:
    get:
      description: |
        Get public profile information about a Spotify user.
      operationId: Users_getUserProfile
      security:
      - oauth_2_0: []
      summary: |
        Get User's Profile
      tags:
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-user_id
      x-accepts: application/json
  /users/{user_id}/playlists:
    get:
      description: |
        Get a list of the playlists owned or followed by a Spotify user.
      operationId: Playlists_getUserPlaylists
      security:
      - oauth_2_0:
        - playlist-read-private
        - playlist-read-collaborative
      summary: |
        Get User's Playlists
      tags:
      - Playlists
      - Users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-user_id-playlists
      x-accepts: application/json
    post:
      description: |
        Create a playlist for a Spotify user. (The playlist will be empty until
        you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)
        Each user is generally limited to a maximum of 11000 playlists.
      operationId: Playlists_createPlaylist
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Create Playlist
      tags:
      - Playlists
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users-user_id-playlists
      x-content-type: application/json
      x-accepts: application/json
  /playlists/{playlist_id}/followers:
    delete:
      description: |
        Remove the current user as a follower of a playlist.
      operationId: Users_unfollowPlaylist
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Unfollow Playlist
      tags:
      - Users
      - Playlists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--playlists-playlist_id-followers
      x-accepts: application/json
    put:
      description: |
        Add the current user as a follower of a playlist.
      operationId: Users_followPlaylist
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Follow Playlist
      tags:
      - Users
      - Playlists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--playlists-playlist_id-followers
      x-content-type: application/json
      x-accepts: application/json
  /browse/featured-playlists:
    get:
      description: |
        Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).
      operationId: Playlists_getFeatured
      security:
      - oauth_2_0: []
      summary: |
        Get Featured Playlists
      tags:
      - Playlists
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MultipleIntegrations'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--browse-featured-playlists
      x-accepts: application/json
  /browse/categories:
    get:
      description: |
        Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
      operationId: Categories_listSeveral
      security:
      - oauth_2_0: []
      summary: |
        Get Several Browse Categories
      tags:
      - Categories
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--browse-categories
      x-accepts: application/json
  /browse/categories/{category_id}:
    get:
      description: |
        Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
      operationId: Categories_getSingle
      security:
      - oauth_2_0: []
      summary: |
        Get Single Browse Category
      tags:
      - Categories
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--browse-categories-category_id
      x-accepts: application/json
  /browse/categories/{category_id}/playlists:
    get:
      description: |
        Get a list of Spotify playlists tagged with a particular category.
      operationId: Playlists_getCategoryPlaylists
      security:
      - oauth_2_0: []
      summary: |
        Get Category's Playlists
      tags:
      - Playlists
      - Categories
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--browse-categories-category_id-playlists
      x-accepts: application/json
  /playlists/{playlist_id}/images:
    get:
      description: |
        Get the current image associated with a specific playlist.
      operationId: Playlists_getCoverImage
      security:
      - oauth_2_0: []
      summary: |
        Get Playlist Cover Image
      tags:
      - Playlists
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--playlists-playlist_id-images
      x-accepts: application/json
    put:
      description: |
        Replace the image used to represent a specific playlist.
      operationId: Playlists_replaceCoverImage
      security:
      - oauth_2_0:
        - ugc-image-upload
        - playlist-modify-public
        - playlist-modify-private
      summary: |
        Add Custom Playlist Cover Image
      tags:
      - Playlists
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: image/jpeg
      x-accepts: application/json
  /browse/new-releases:
    get:
      description: |
        Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player’s “Browse” tab).
      operationId: Albums_getNewReleases
      security:
      - oauth_2_0: []
      summary: |
        Get New Releases
      tags:
      - Albums
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MultipleIntegrations'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--browse-new-releases
      x-accepts: application/json
  /me/following:
    delete:
      description: |
        Remove the current user as a follower of one or more artists or other Spotify users.
      operationId: Users_unfollowArtistsUsers
      security:
      - oauth_2_0:
        - user-follow-modify
      summary: |
        Unfollow Artists or Users
      tags:
      - Users
      - Artists
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
    get:
      description: |
        Get the current user's followed artists.
      operationId: Users_getFollowedArtists
      security:
      - oauth_2_0:
        - user-follow-read
      summary: |
        Get Followed Artists
      tags:
      - Users
      - Library
      - Artists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-following
      x-accepts: application/json
    put:
      description: |
        Add the current user as a follower of one or more artists or other Spotify users.
      operationId: Users_followArtistsOrUsers
      security:
      - oauth_2_0:
        - user-follow-modify
      summary: |
        Follow Artists or Users
      tags:
      - Users
      - Artists
      - Library
      x-konfig-operation-can-have-single-parameter: false
      x-content-type: application/json
      x-accepts: application/json
  /me/following/contains:
    get:
      description: |
        Check to see if the current user is following one or more artists or other Spotify users.
      operationId: Users_checkFollowingArtistsUsers
      security:
      - oauth_2_0:
        - user-follow-read
      summary: |
        Check If User Follows Artists or Users
      tags:
      - Users
      - Artists
      - Library
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-following-contains
      x-accepts: application/json
  /playlists/{playlist_id}/followers/contains:
    get:
      description: |
        Check to see if one or more Spotify users are following a specified playlist.
      operationId: Users_checkIfFollowsPlaylist
      security:
      - oauth_2_0: []
      summary: |
        Check if Users Follow Playlist
      tags:
      - Users
      - Playlists
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--playlists-playlist_id-followers-contains
      x-accepts: application/json
  /audio-features:
    get:
      description: |
        Get audio features for multiple tracks based on their Spotify IDs.
      operationId: Tracks_getMultipleAudioFeatures
      security:
      - oauth_2_0: []
      summary: |
        Get Several Tracks' Audio Features
      tags:
      - Tracks
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--audio-features
      x-accepts: application/json
  /audio-features/{id}:
    get:
      description: |
        Get audio feature information for a single track identified by its unique
        Spotify ID.
      operationId: Tracks_getAudioFeaturesById
      security:
      - oauth_2_0: []
      summary: |
        Get Track's Audio Features
      tags:
      - Tracks
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--audio-features-id
      x-accepts: application/json
  /audio-analysis/{id}:
    get:
      description: |
        Get a low-level audio analysis for a track in the Spotify catalog. The audio analysis describes the track’s structure and musical content, including rhythm, pitch, and timbre.
      operationId: Tracks_getAudioAnalysis
      security:
      - oauth_2_0: []
      summary: |
        Get Track's Audio Analysis
      tags:
      - Tracks
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--audio-analysis-id
      x-accepts: application/json
  /recommendations:
    get:
      description: |
        Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.

        For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.
      operationId: Tracks_getRecommendations
      security:
      - oauth_2_0: []
      summary: |
        Get Recommendations
      tags:
      - Tracks
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--recommendations
      x-accepts: application/json
  /recommendations/available-genre-seeds:
    get:
      description: |
        Retrieve a list of available genres seed parameter values for [recommendations](/documentation/web-api/reference/get-recommendations).
      operationId: Genres_getAvailableSeeds
      security:
      - oauth_2_0: []
      summary: |
        Get Available Genre Seeds
      tags:
      - Genres
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--recommendations-available-genre-seeds
      x-accepts: application/json
  /me/player:
    get:
      description: |
        Get information about the user’s current playback state, including track or episode, progress, and active device.
      operationId: Player_getCurrentPlaybackState
      security:
      - oauth_2_0:
        - user-read-playback-state
      summary: |
        Get Playback State
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-player
      x-accepts: application/json
    put:
      description: |
        Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_transferPlaybackToNewDevice
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Transfer Playback
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-player
      x-content-type: application/json
      x-accepts: application/json
  /me/player/devices:
    get:
      description: |
        Get information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.
      operationId: Player_getAvailableDevices
      security:
      - oauth_2_0:
        - user-read-playback-state
      summary: |
        Get Available Devices
      tags:
      - Player
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-player-devices
      x-accepts: application/json
  /me/player/currently-playing:
    get:
      description: |
        Get the object currently being played on the user's Spotify account.
      operationId: Player_getCurrentlyPlayingTrack
      security:
      - oauth_2_0:
        - user-read-currently-playing
      summary: |
        Get Currently Playing Track
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-player-currently-playing
      x-accepts: application/json
  /me/player/play:
    put:
      description: |
        Start a new context or resume current playback on the user's active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_startPlayback
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Start/Resume Playback
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-player-play
      x-content-type: application/json
      x-accepts: application/json
  /me/player/pause:
    put:
      description: |
        Pause playback on the user's account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_pausePlayback
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Pause Playback
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-player-pause
      x-accepts: application/json
  /me/player/next:
    post:
      description: |
        Skips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_skipToNextTrack
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Skip To Next
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--me-player-next
      x-accepts: application/json
  /me/player/previous:
    post:
      description: |
        Skips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_skipToPreviousTrack
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Skip To Previous
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--me-player-previous
      x-accepts: application/json
  /me/player/seek:
    put:
      description: |
        Seeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_seekToPosition
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Seek To Position
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-player-seek
      x-accepts: application/json
  /me/player/repeat:
    put:
      description: |
        Set the repeat mode for the user's playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_setRepeatMode
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Set Repeat Mode
      tags:
      - Player
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-player-repeat
      x-accepts: application/json
  /me/player/volume:
    put:
      description: |
        Set the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_setPlaybackVolume
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Set Playback Volume
      tags:
      - Player
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-player-volume
      x-accepts: application/json
  /me/player/shuffle:
    put:
      description: |
        Toggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_togglePlaybackShuffle
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Toggle Playback Shuffle
      tags:
      - Player
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--me-player-shuffle
      x-accepts: application/json
  /me/player/recently-played:
    get:
      description: |
        Get tracks from the current user's recently played tracks.
        _**Note**: Currently doesn't support podcast episodes._
      operationId: Player_getRecentlyPlayedTracks
      security:
      - oauth_2_0:
        - user-read-recently-played
      summary: |
        Get Recently Played Tracks
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-player-recently-played
      x-accepts: application/json
  /me/player/queue:
    get:
      description: |
        Get the list of objects that make up the user's queue.
      operationId: Player_getUserQueue
      security:
      - oauth_2_0:
        - user-read-currently-playing
        - user-read-playback-state
      summary: |
        Get the User's Queue
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--me-player-queue
      x-accepts: application/json
    post:
      description: |
        Add an item to the end of the user's current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
      operationId: Player_addItemToQueue
      security:
      - oauth_2_0:
        - user-modify-playback-state
      summary: |
        Add Item to Playback Queue
      tags:
      - Player
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--me-player-queue
      x-accepts: application/json
  /markets:
    get:
      description: |
        Get the list of markets where Spotify is available.
      operationId: Markets_listAvailable
      security:
      - oauth_2_0: []
      summary: |
        Get Available Markets
      tags:
      - Markets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--markets
      x-accepts: application/json
components:
  securitySchemes:
    oauth_2_0:
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          scopes:
            app-remote-control: |
              Communicate with the Spotify app on your device.
            playlist-read-private: |
              Access your private playlists.
            playlist-read-collaborative: |
              Access your collaborative playlists.
            playlist-modify-public: |
              Manage your public playlists.
            playlist-modify-private: |
              Manage your private playlists.
            user-library-read: |
              Access your saved content.
            user-library-modify: |
              Manage your saved content.
            user-read-private: |
              Access your subscription details.
            user-read-email: |
              Get your real email address.
            user-follow-read: |
              Access your followers and who you are following.
            user-follow-modify: |
              Manage your saved content.
            user-top-read: |
              Read your top artists and content.
            user-read-playback-position: |
              Read your position in content you have played.
            user-read-playback-state: |
              Read your currently playing content and Spotify Connect devices information.
            user-read-recently-played: |
              Access your recently played items.
            user-read-currently-playing: |
              Read your currently playing content.
            user-modify-playback-state: |
              Control playback on your Spotify clients and Spotify Connect devices.
            ugc-image-upload: |
              Upload images to Spotify on your behalf.
            streaming: |
              Play content and control playback on your other devices.
          tokenUrl: https://accounts.spotify.com/api/token
      type: oauth2
      x-konfig-globally-required-security: true
  x-spotify-policy:
    metadataPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
    metadataWithMachineLearningPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
    - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
    playerPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/CommercialStreaming'
    - $ref: '#/components/x-spotify-policy/policies/ContentAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Synchronization'
    - $ref: '#/components/x-spotify-policy/policies/Broadcasting'
    downloading:
      $ref: '#/components/x-spotify-policy/policies/Downloading'

